---
title: "FORRT Contributor Analyses"
date: "10 May, 2025"
always_allow_html: true
output:
  html_document:
    self_contained: false
    keep_md:     true
    lib_dir:     "htmlwidgets_libs"
type: contributors_analysis
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE, fig.path = ""
)
```

```{r Load Libraries}
library(readxl)  # For reading Excel files
library(dplyr)   # For data manipulation
library(ggplot2) # For visualization
library(tidyr)   # For reshaping data
library(googlesheets4) # For reading Google Sheets
library(stringr) # For removing unwanted characters around strings
library(gridExtra) # For arranging figures
library(glue) # For printing text
library(tidygraph) # 
library(ggraph)
library(igraph)
library(visNetwork)
library(Matrix)
```

```{r Read sheets from automation source}

# Define Google Sheet URL for Automation Source
google_sheet_url_automation <- "https://docs.google.com/spreadsheets/d/1MUD54FQUhfcBKrvr5gCYoh2wgbJ6Lf7oAJRAqsQ-Nag/edit"

# Get sheet names
gs4_deauth()
sheets <- sheet_names(google_sheet_url_automation)

# Exclude the first four Automation Source sheets
relevant_sheets <- sheets[-c(1,2,3,4)]

# Exclude 'full' sheets
relevant_sheets <- relevant_sheets[!grepl(" - full$", relevant_sheets)]

# Read all relevant sheets into a list and remove rows without last names
internal_links <- read_sheet(google_sheet_url_automation, sheet = "INTERNAL LINKS") %>% 
  select(`Project Name`) # Extract project names

data_list <- lapply(relevant_sheets, function(sheet) {
  # Read the content of the current sheet
  df <- read_sheet(google_sheet_url_automation, sheet = sheet)
  # Remove rows where the `Surname` is missing or empty
  df <- df %>% filter(!is.na(`Surname`) & `Surname` != "")
  # Match the `Project Name` using the sheet name (assuming sheet name is the identifier)
  project_name <- internal_links$`Project Name`[internal_links$`Project Name` == sheet]
  # If a match is found, assign the `Project Name`, else set to NA
  if (length(project_name) > 0) {
    df <- df %>% mutate(`Project Name` = project_name)
  } else {
    df <- df %>% mutate(`Project Name` = NA)
  }
  df
})

# Combine all sheets into one dataframe
dt <- bind_rows(data_list, .id = "Source_Sheet")

# Move project name column to first position 
dt <- dt %>%
  select(`Project Name`, everything())

# Remove PM column as it is unncessary and might cause problems with binding
dt <- dt %>%
  select(-`Project Managers`)
```

```{r Read sheets from leads tenzing}

# Define Google Sheet URL for Leads Tenzing 
google_sheet_url_leads <- "https://docs.google.com/spreadsheets/d/1roy-sZTxyXENA5c5IIV7IIemYvzbzs7zojUN2yIpi58/edit?gid=0#gid=0"

# Get sheet names
leads_sheets <- sheet_names(google_sheet_url_leads)

# Exclude the second Leads Tenzing sheet
relevant_leads_sheets <- leads_sheets[-c(2)]

# Read the Leads Tenzing sheet
leads_df <- read_sheet(google_sheet_url_leads)

# Rename columns and select relevant ones
leads_df <- leads_df %>%
  rename(
    `Project Name` = `FORRT project(s)`,
    `ORCID iD` = `ORCID`
  ) %>%
  select(`First name`, `Middle name`, `Surname`, `Project Name`, `Role`, `ORCID iD`)

# Create a column to mark the presence of a role and group by individual
leads_df <- leads_df %>%
  mutate(has_role = TRUE) %>%  # Mark with TRUE for individuals having a role
  distinct(`First name`, `Middle name`, `Surname`, `Project Name`, `ORCID iD`, `Role`, .keep_all = TRUE)  # Remove duplicates

# Pivot the data to create a column for each leadership role type, removing director
leads_df <- leads_df %>%
  pivot_wider(names_from = `Role`, values_from = `has_role`, values_fill = list(has_role = FALSE)) %>%
  select(-Director, -`Operations Coordinator`)  # Drop the 'Director' and Operations Coordinator columns

```

```{r Combine roles from leads tenzing with automation source}

# Combine leads tenzing rows with automation source
dt <- bind_rows(dt, leads_df)
```

```{r Trim Values For Consistency}

# Trim names and ORCIDs to ensure inconsistent Tenzing entries are not counted separately 
dt <- dt %>%
  mutate(
    `First name` = str_trim(str_replace_all(`First name`, "\\*", "")),  # Remove * and trim spaces
    `Middle name` = str_trim(str_replace_all(`Middle name`, "\\*", "")) %>% str_sub(1, 1),  # Remove *, trim spaces, and keep first letter
    `Surname` = str_trim(str_replace_all(`Surname`, "\\*", "")),  # Remove * and trim spaces
    `ORCID iD` = str_trim(str_remove(`ORCID iD`, "https://orcid.org/"))  # Remove ORCID URL prefix and trim spaces
  )
```

```{r ensure Conceptualization is logical}
dt$Conceptualization <- as.logical(dt$Conceptualization)
```

```{r Metrics}
# Count unique contributors (only use surname and first name at the moment, middle name causes problems)
unique_contributors <- dt %>% 
  distinct(`Surname`, `First name`) %>%
  nrow()

# Contributions per person
contributions_per_person <- dt %>% 
  group_by(`Surname`, `First name`,) %>% 
  summarise(Contributions = n(), .groups = 'drop')

# Mean contributions per person
mean_contributions_per_person <- mean(contributions_per_person$Contributions)
```

```{r Project Engagement}
count_projects <- dt %>%
  summarise(n_distinct(`Project Name`))

count_projects <- as.integer(count_projects)

# Contributors per project
project_contributors <- dt %>% 
  distinct(`Project Name`, `Surname`, `First name`, `Middle name`) %>%  # Remove duplicate contributor entries
  group_by(`Project Name`) %>% 
  summarise(Unique_Contributors = n(), .groups = 'drop') %>%  # Count distinct names
  arrange(desc(Unique_Contributors)) 

# Reorder the 'Project Name' based on the number of unique contributors (descending)
project_contributors$`Project Name` <- factor(project_contributors$`Project Name`, 
                                              levels = project_contributors$`Project Name`)

# Roles and contributions distribution
dt_long <- dt %>%
  pivot_longer(
    cols = "Conceptualization" | starts_with("Writing") | 
           "Data curation" | "Formal analysis" |
           "Funding acquisition" | "Investigation" |
           "Methodology" | "Project administration" |
           "Resources" | "Software" | "Supervision" | "Validation" |
           "Visualization" | "Project manager" |
           "Project Coordinators" | "Project lead" | "Project co-lead",
    names_to = "Role", 
    values_to = "Contribution"
  ) %>%
  filter(Contribution == TRUE)

role_distribution <- dt_long %>%
  count(Role, sort = TRUE)

mean_project_contributors <- mean(project_contributors$Unique_Contributors)
```

```{r Summary for Website}
output <- glue("
As of {format(Sys.Date(), '%d %B %Y')}, FORRT has a total of {sprintf('%d', count_projects)} completed or ongoing projects and support teams, with a total of {format(unique_contributors, big.mark = ',')} contributors. There is an average (mean) of {sprintf('%.2f', mean_contributions_per_person)} contributions per person across all FORRT projects, and the average number of contributors per project is {sprintf('%.2f', mean_project_contributors)}. You can see the full list of FORRT contributors and their individual contributions [here](https://forrt.org/contributors/).")
```

`r output`


```{r Basic visualizations}
# Contributors per project

# Keep only the top 10 projects based on Unique_Contributors
project_contributors <- project_contributors %>%
  arrange(desc(Unique_Contributors)) %>%
  slice_head(n = 10)

# Get the first three project names from the sorted order
top_projects <- project_contributors$`Project Name`[1:5]

# Add labels only for these projects
project_contributors <- project_contributors %>%
  mutate(label = ifelse(`Project Name` %in% top_projects, as.character(`Project Name`), NA))

# Plot
projects_plot <- ggplot(project_contributors, aes(x = `Project Name`, y = Unique_Contributors)) +
  geom_bar(stat = "identity", fill = "#A52828", color = "#323232", alpha = 0.8) +  
  geom_text(aes(label = label), hjust = 0, nudge_x = -0.3, vjust = 1.0, nudge_y = 9, size = 3, na.rm = TRUE) +  # Adjusted vjust and nudge_y
  labs(title = "Contributors for FORRT's 10 Biggest Projects", 
       x = "Projects",  
       y = "Number of Contributors") +
  theme_minimal(base_size = 18) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
        axis.text.x = element_blank(),  
        axis.ticks.x = element_blank(), 
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 14),
        panel.background = element_rect(fill = "#fefdf6", color = NA),  # No panel border
        plot.background = element_rect(fill = "#fefdf6", color = NA), 
        panel.border = element_blank(),                                
        panel.spacing = unit(0, "lines"))

# Roles in projects
roles_plot <- ggplot(role_distribution, aes(x = reorder(Role, n), y = n)) +
  geom_bar(stat = "identity", fill = "#A52828", color = "#323232", alpha = 0.8) +
  coord_flip() +
  labs(title = "Distribution of Contributions Across Roles", 
       x = "Role", 
       y = "Number of People") +
  theme_minimal(base_size = 14) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 16),  # Set title size to 16
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        panel.background = element_rect(fill = "#fefdf6", color = NA),  # No panel border
        plot.background = element_rect(fill = "#fefdf6", color = NA),   # No plot border
        panel.border = element_blank(), # Explicitly blank
        panel.spacing = unit(0, "lines"))
```


```{r projects-plot, fig.alt = "Bar chart of contributors per project"}
projects_plot
```

```{r roles-plot, fig.alt = "Bar chart of contributions by Tenzing role"}
roles_plot
```


```{r dt long}
dt_long <- dt_long %>% 
  rowwise() %>% 
  mutate(Contributor = paste(na.omit(c(`Surname`, `First name`)), collapse = " ")) %>% 
  mutate(Lead = if_else(Role %in% c("lead", "co-lead"), Role, "other"))
```
## Network of Contributors

```{r contributor co-occurrences}
# get co-occurences
Contributor_Project <- xtabs(~ `Project Name` + Contributor, 
                                data=dt_long %>% 
                               select(`Project Name`, Contributor) %>% 
                               unique(), 
                                sparse = TRUE)

Contributor_occur <- crossprod(Contributor_Project, Contributor_Project)
```

```{r contributor-network, fig.alt = "Network chart of FORRT contributors"}
Contributor_nodes_n <- dt_long %>%
  group_by(Contributor) %>% 
  count(Contributor)

colnames(Contributor_nodes_n) <- c("id", "value")

ContributorGroups_nodes <- dt_long %>% 
  select(Contributor, `Project Name`) %>% 
  unique() %>% 
  group_by(Contributor) %>% 
  mutate(Projects = paste0(`Project Name`, collapse = ",")) %>% 
  select(Contributor, Projects) %>% 
  unique()

colnames(ContributorGroups_nodes) <- c("id", "projects")

Contributor_nodes <- left_join(Contributor_nodes_n,
                               ContributorGroups_nodes)
Contributor_nodes$title <- paste0(Contributor_nodes$id,"<br>", gsub(patter = ",", replacement = "<br>", x = Contributor_nodes$projects))

Contributor_edges <- which(upper.tri(Contributor_occur), arr.ind = TRUE) %>%
  as.data.frame() %>%
  mutate(
    from = rownames((Contributor_occur))[row],
    to   = colnames((Contributor_occur))[col],
    width_n = (Contributor_occur)[cbind(row, col)]
  ) %>%
  filter(width_n > 0) %>%  # Optional: remove 0s
  mutate(width = (width_n/10)^(3)) %>% 
  select(from, to, width) 

## add one hidden edge that will move the Chinese translator team closer to the center
additional_hidden_edge <- data.frame(from = c("Fang Cathy", "Chen Liangjie", "Jin Shuxian", "Yang Jinbiao", "Liu Ruoting", "Wang Xinyu", "Xu Yu", "Ji Xuejun", "Wang Zixi"), 
                                     to = c("Azevedo Flavio"), 
                                     width = 0.0,
                                     hidden = TRUE)

Contributor_edges_plot <- rbind(Contributor_edges %>% 
  mutate(hidden = F), additional_hidden_edge)

visNetwork(Contributor_nodes,
           Contributor_edges_plot,
           width = "100%",
           height = "600px"
) %>%
  visIgraphLayout(layout = "layout_nicely",
                  randomSeed = 1001)  %>%
  visPhysics(
    enabled = TRUE,
    stabilization = list(
      enabled = TRUE,
      iterations = 100,
      fit = FALSE
    ),
    solver = "forceAtlas2Based",
    forceAtlas2Based = list(
      gravitationalConstant = -200,
      centralGravity = 0.05,         
      springLength = 50,
      springConstant = 0.005,        
      damping = 0.4,
      avoidOverlap = 0.8 
    )
  ) %>%
  visEdges(color = list(opacity = 0.1)) %>%
  visNodes(
    font = list(
      size = 5,
      strokeWidth = 1,
      strokeColor = "white"
    ),
    size = 7,
    borderWidth = 0,
    color = list(
      background = "#353839",
      highlight = list(
        background = "#A52828",
        border = "darkred"
      )
    ),
    scaling = list(
      min = 5,
      max = 25
    )
  ) %>% 
  visGroups(useDefaultGroups = FALSE) %>% 
  # Combined interaction settings
  visInteraction(
    zoomView = 0.2,
    zoom = TRUE,
    dragNodes = TRUE,
    dragView = TRUE,
    hover = TRUE,
    hoverConnectedEdges = TRUE,
    selectable = TRUE,
    multiselect = TRUE,
    navigationButtons = TRUE
  ) %>%
  visOptions(
    highlightNearest = list(
      enabled = TRUE, 
      degree = 1, 
      hover = TRUE,
      algorithm = "hierarchical"
    ),
    nodesIdSelection = list(enabled = TRUE, style = "width: 200px;"),
    selectedBy = list(variable = "projects", multiple = TRUE, 
                     style = "width: 200px; background: #f8f8f8;")
  ) %>%
  htmlwidgets::onRender("
    function(el, x) {
      var network = this;
      network.on('stabilized', function(params) {
        network.fit({nodes: [], animation: {duration: 100}});
      });
      network.on('click', function(params) {
        if (params.nodes.length === 0) {
          network.body.data.nodes.update(
            network.body.data.nodes.getIds().map(function(id) {
              return {id: id, color: {background: '#353839'}};
            })
          );
        }
      });
      network.on('selectNode', function(params) {
        network.body.data.nodes.update(
          network.body.data.nodes.getIds().map(function(id) {
            return {id: id, color: {background: '#353839'}};
          })
        );
        network.body.data.nodes.update({
          id: params.nodes[0],
          color: {background: '#A52828'}
        });
      });
    }
  ")  
```
