name: close-stale

on:
  schedule:
  - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  close-stale:
    runs-on: ubuntu-24.04
    steps:
    - name: Close Stale Issues
      uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been inactive for more than 90 days. If there is no further activity, it will be automatically closed in seven days time. You can reopen the issue if it is still relevant.'
        stale-pr-message: 'This pull request has been inactive for more than 90 days. If there is no further activity, it will be automatically closed in seven days time. You can reopen the pull request if it is still relevant.'
        close-issue-message: 'This issue has been automatically closed due to it being stale for more than 7 days. Please feel free to reopen if you still want this issue.'
        close-pr-message: 'This pull request has been automatically closed due it being stale for more than 7 days. Please feel free to reopen if you still want to submit this pull request.'
        stale-issue-label: stale
        stale-pr-label: stale
        days-before-stale: 60
        days-before-close: 7
        exempt-issue-labels: 'bug'
        exempt-pr-labels: 'bug'
        delete-branch: false # Do not delete the branch, in case someone wants to reopen the PR in the future