name: Trigger Deploy on Command

on:
  issue_comment:
    types: [created]

jobs:
  deploy-test:
    if: startsWith(github.event.comment.body, '/deploy')
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger deployment workflow
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: /deploy
          workflow: deploy.yml
          ref: main
          inputs:
            pr_number: ${{ github.event.issue.number }}
