name: "Pull Request Labeler"
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - closed
  schedule:
    - cron: "0 1 * * 1"
  workflow_dispatch:

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Laber PR
      uses: actions/labeler@v5
