# Please note that this pipeline is currently not working as expected. This is being investigated.
name: Deploy Preview

on:
  workflow_dispatch:
  

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.0'

      - name: Build and Deploy
        run: |
          hugo --gc --minify -b $DEPLOY_PRIME_URL
          DEPLOY_URL=$(curl -s -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" "https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys" | jq -r '.[0].deploy_url')
          DEPLOY_LOG_URL=$(curl -s -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" "https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys" | jq -r '.[0].ssl_url')
          LATEST_COMMIT=$(git rev-parse --short HEAD)
          MESSAGE="✅ Deploy Preview for $GITHUB_SHA ready!\n\nName Link\n🔨 Latest commit $LATEST_COMMIT\n🔍 Latest deploy log $DEPLOY_LOG_URL\n😎 Deploy Preview $DEPLOY_URL"
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -d '{"body":"'"$MESSAGE"'"}' "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments"
        env:
          DEPLOY_PRIME_URL: ${{ secrets.DEPLOY_PRIME_URL }}
          NETLIFY_SITE_ID: ${{ secrets.14b7d153-85d1-479d-b19f-1843019d0908 }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
